# Generated by Django 4.2.11 on 2024-10-03 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_calendar_created_at_alter_calendar_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='page_permissions',
            field=models.ManyToManyField(blank=True, related_name='page', to='user.page', verbose_name='Page Permissions'),
        ),
    ]
