# Generated by Django 4.2.11 on 2024-10-14 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_seller_page_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='page_permissions',
            field=models.ManyToManyField(blank=True, null=True, related_name='page', to='user.page', verbose_name='Page Permissions'),
        ),
    ]
