# Generated by Django 4.2.11 on 2024-10-31 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name')),
                ('status', models.CharField(choices=[('active', 'Active'), ('in_progress', 'In Progress'), ('in_base', 'In Base'), ('frozen', 'Frozen'), ('archived', 'Archived'), ('deleted', 'Deleted')], default='in_progress', max_length=20, verbose_name='Status')),
                ('reactivate_data', models.DateTimeField(blank=True, null=True, verbose_name='Reactivate Data')),
                ('during_at', models.DateTimeField(blank=True, null=True, verbose_name='During')),
                ('extra_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Extra Phone')),
                ('telegram_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telegram Phone')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('recall_date', models.DateTimeField(blank=True, null=True, verbose_name='Recall Date')),
                ('status_changed_at', models.DateTimeField(null=True, verbose_name='Status Changed at')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('status', models.BooleanField(default=False, verbose_name='Status')),
                ('latitude', models.FloatField(default=0, verbose_name='Latitude')),
                ('longitude', models.FloatField(default=0, verbose_name='Longitude')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
            },
        ),
        migrations.CreateModel(
            name='MedicalSector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('status', models.BooleanField(default=False, verbose_name='Status')),
                ('inn_number', models.BigIntegerField(default=0, verbose_name='Inner Number')),
            ],
            options={
                'verbose_name': 'Medical Sector',
                'verbose_name_plural': 'Medical Sectors',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('image', models.ImageField(blank=True, null=True, upload_to='payment_type/', verbose_name='Image')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('image', models.ImageField(upload_to='products/', verbose_name='Image')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sale Amount')),
                ('approved_at', models.DateTimeField(auto_now_add=True, verbose_name='Approved At')),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('status', models.BooleanField(default=False, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Sector',
                'verbose_name_plural': 'Sectors',
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('status', models.BooleanField(default=False, verbose_name='Status')),
                ('image', models.ImageField(blank=True, null=True, upload_to='source/', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Source',
                'verbose_name_plural': 'Sources',
            },
        ),
        migrations.CreateModel(
            name='StatusChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('type', models.CharField(choices=[('customer', 'Customer'), ('comment', 'Comment'), ('sold', 'Sold')], default='comment', max_length=20, verbose_name='Type')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('archived', 'Archived'), ('deleted', 'Deleted')], default='pending', max_length=20, verbose_name='Status')),
                ('new_status', models.CharField(blank=True, choices=[('active', 'Active'), ('in_progress', 'In Progress'), ('in_base', 'In Base'), ('frozen', 'Frozen'), ('archived', 'Archived'), ('deleted', 'Deleted')], max_length=20, null=True, verbose_name='New Status')),
                ('comment_status', models.BooleanField(blank=True, default=None, null=True)),
                ('sold_status', models.BooleanField(blank=True, default=None, null=True)),
                ('text', models.CharField(max_length=255, verbose_name='Text')),
                ('admin_response', models.CharField(max_length=255, verbose_name='Admin Response')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approved At')),
            ],
            options={
                'verbose_name': 'Status Change Request',
                'verbose_name_plural': 'Status Change Requests',
            },
        ),
        migrations.CreateModel(
            name='SubLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('status', models.BooleanField(default=False, verbose_name='Status')),
                ('archive', models.BooleanField(default=False, verbose_name='Archive')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_locations', to='common.location', verbose_name='Location')),
            ],
            options={
                'verbose_name': 'Sub Location',
                'verbose_name_plural': 'Sub Locations',
            },
        ),
    ]
