# Generated by Django 4.2.11 on 2024-10-31 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sublocation',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.seller', verbose_name='Seller'),
        ),
        migrations.AddField(
            model_name='statuschangerequest',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='status_change_requests_comment', to='user.comment', verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='statuschangerequest',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='status_change_requests_customer', to='common.customer', verbose_name='Customer'),
        ),
        migrations.AddField(
            model_name='statuschangerequest',
            name='sale',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_change_request', to='common.sale', verbose_name='Sale'),
        ),
        migrations.AddField(
            model_name='statuschangerequest',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_change_requests_seller', to='user.seller', verbose_name='Seller'),
        ),
        migrations.AddField(
            model_name='source',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.seller', verbose_name='Seller'),
        ),
        migrations.AddField(
            model_name='source',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sources', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='sector',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sectors', to='user.seller', verbose_name='Seller'),
        ),
        migrations.AddField(
            model_name='sector',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='sale',
            name='product',
            field=models.ManyToManyField(to='common.product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='sale',
            name='request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='sale_request', to='common.statuschangerequest'),
        ),
        migrations.AddField(
            model_name='sale',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.seller', verbose_name='Seller'),
        ),
        migrations.AddField(
            model_name='sale',
            name='sub_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.sublocation', verbose_name='SubLocation'),
        ),
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.seller', verbose_name='Seller'),
        ),
        migrations.AddField(
            model_name='product',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='medicalsector',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medical_location', to='common.sublocation', verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='medicalsector',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medical_sector', to='common.sector', verbose_name='Sector'),
        ),
        migrations.AddField(
            model_name='medicalsector',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.seller', verbose_name='Seller'),
        ),
        migrations.AddField(
            model_name='location',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.seller', verbose_name='Seller'),
        ),
        migrations.AddField(
            model_name='customer',
            name='copy_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copies', to='common.customer', verbose_name='Copy Customer'),
        ),
        migrations.AddField(
            model_name='customer',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='common.location', verbose_name='Sub Location'),
        ),
        migrations.AddField(
            model_name='customer',
            name='medical',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='common.medicalsector', verbose_name='Medical Sector'),
        ),
        migrations.AddField(
            model_name='customer',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='common.paymentmethod'),
        ),
        migrations.AddField(
            model_name='customer',
            name='payment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='common.paymenttype'),
        ),
        migrations.AddField(
            model_name='customer',
            name='products',
            field=models.ManyToManyField(related_name='customers', to='common.product', verbose_name='Products'),
        ),
        migrations.AddField(
            model_name='customer',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='common.sector', verbose_name='Sector'),
        ),
        migrations.AddField(
            model_name='customer',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='user.seller', verbose_name='Seller'),
        ),
        migrations.AddField(
            model_name='customer',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='common.source', verbose_name='Source'),
        ),
        migrations.AddField(
            model_name='customer',
            name='sub_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='common.sublocation', verbose_name='Sub Location'),
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customers', to=settings.AUTH_USER_MODEL),
        ),
    ]
