# Generated by Django 4.2.16 on 2024-09-25 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sublocation',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.seller', verbose_name='Seller'),
        ),
        migrations.AddField(
            model_name='statuschangerequest',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.comment', verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='statuschangerequest',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_change_requests', to='common.customer', verbose_name='Customer'),
        ),
        migrations.AddField(
            model_name='statuschangerequest',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_change_requests', to='user.seller', verbose_name='Seller'),
        ),
        migrations.AddField(
            model_name='source',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.seller', verbose_name='Seller'),
        ),
        migrations.AddField(
            model_name='sector',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sectors', to='user.seller', verbose_name='Seller'),
        ),
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.seller', verbose_name='Seller'),
        ),
        migrations.AddField(
            model_name='medicalsector',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.seller', verbose_name='Seller'),
        ),
        migrations.AddField(
            model_name='location',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.seller', verbose_name='Seller'),
        ),
        migrations.AddField(
            model_name='customer',
            name='copy_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copies', to='common.customer', verbose_name='Copy Customer'),
        ),
        migrations.AddField(
            model_name='customer',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='common.location', verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='customer',
            name='medical',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='common.medicalsector', verbose_name='Medical Sector'),
        ),
        migrations.AddField(
            model_name='customer',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='common.paymentmethod'),
        ),
        migrations.AddField(
            model_name='customer',
            name='payment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='common.paymenttype'),
        ),
        migrations.AddField(
            model_name='customer',
            name='products',
            field=models.ManyToManyField(related_name='customers', to='common.product', verbose_name='Products'),
        ),
        migrations.AddField(
            model_name='customer',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='common.sector', verbose_name='Sector'),
        ),
        migrations.AddField(
            model_name='customer',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='user.seller', verbose_name='Seller'),
        ),
        migrations.AddField(
            model_name='customer',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='common.source', verbose_name='Source'),
        ),
    ]
