# Generated by Django 4.2.16 on 2024-09-25 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalsector',
            name='inn_number',
            field=models.IntegerField(default=0, verbose_name='Inner Number'),
        ),
    ]
