# Generated by Django 4.2.11 on 2024-10-14 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_seller_page_permissions'),
        ('common', '0007_delete_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalsector',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medical_location', to='common.location', verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='medicalsector',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medical_sector', to='common.sector', verbose_name='Sector'),
        ),
        migrations.AddField(
            model_name='sector',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sector', to='common.location', verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='statuschangerequest',
            name='sold_status',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='medical',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='common.medicalsector', verbose_name='Medical Sector'),
        ),
        migrations.AlterField(
            model_name='statuschangerequest',
            name='comment_status',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='statuschangerequest',
            name='type',
            field=models.CharField(choices=[('customer', 'Customer'), ('comment', 'Comment'), ('sold', 'Sold')], default='comment', max_length=20, verbose_name='Type'),
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sale Amount')),
                ('approved_at', models.DateTimeField(auto_now_add=True, verbose_name='Approved At')),
                ('product', models.ManyToManyField(to='common.product', verbose_name='Product')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sale_request', to='common.statuschangerequest')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.seller', verbose_name='Seller')),
                ('sub_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.sublocation', verbose_name='SubLocation')),
            ],
        ),
        migrations.AddField(
            model_name='statuschangerequest',
            name='sale',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_change_request', to='common.sale', verbose_name='Sale'),
        ),
    ]
